ALTER TABLE accounts ADD COLUMN IF NOT EXISTS source_json JSONB;

CREATE TABLE IF NOT EXISTS dashboard_state (
  key TEXT PRIMARY KEY,
  value_json JSONB NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
